{
	label_NEW:"NOVO",
	label_VISUALIZEDBYRESTAURANT:"Novo",	
	label_PREPARING:"Em preparo",
	label_INTRANSIT:"Em tr&acirc;nsito",
	label_DELIVERED:"Entregue",
	label_EVALUATED:"Avaliado pelo cliente",
	label_WAITING_CUSTOMER:"Aguardando cliente",
	label_CANCELLED:"Cancelado",
	label_EXPIRED:"Vencido",
	
	label_CLIENT_NEW:"Aguardando restaurante",
	label_CLIENT_VISUALIZEDBYRESTAURANT:"Restaurante avaliando",	
	label_CLIENT_PREPARING:"Aceito e em preparo",
	label_CLIENT_INTRANSIT:"Em tr&acirc;nsito",
	label_CLIENT_DELIVERED:"Entregue",
	label_CLIENT_EVALUATED:"Avaliado pelo cliente",
	label_CLIENT_WAITING_CUSTOMER:"Aguardando cliente",
	label_CLIENT_CANCELLED:"Cancelado",
	label_CLIENT_EXPIRED:"Vencido",
	
	
	rankingSiteText_0:"1o pedido no site",
	rankingSiteText_1:"2o pedido no site",
	rankingSiteText_2:"3o pedido no site",
	rankingSiteText:"${0} pedidos no site",
	rankingRestText_0:"1o pedido no restaurante",
	rankingRestText_1:"2o pedido no restaurante",
	rankingRestText_2:"3o pedido no restaurante",
	rankingRestText:"${0} pedidos no restaurante",
	paymentType_CHEQUE:"Em cheque",
	paymentType_INCASH:"Em dinheiro<br>troco para ${0}",
	paymentType_PAYPAL:"Online",
	paymentType_VISAMACHINE:"Visa cr&eacute;dito",
	paymentType_VISADEBITMACHINE:"Visa d&eacute;bito",
	paymentType_VISAVOUCHERMACHINE:"Visa Vale",
	paymentType_AMEXMACHINE:"M&aacute;quina AMEX",
	paymentType_MASTERMACHINE:"Mastercard cr&eacute;dito",
	paymentType_MASTERDEBITMACHINE:"Mastercard d&eacute;bito",
	paymentType_TRMACHINE:"M&aacute;quina TR",
	paymentType_VRSMART:"M&aacute;quina VRSmart",
	paymentType_TRVOUCHER:"Vale papel TR",
	paymentType_TRSODEXHO:"M&aacute;quina SODEXHO",
	orderDetailsTitle:"Detalhes Pedido",
	confirmCancelInitial:"Voc&ecirc; tem certeza que deseja cancelar esse pedido?",
	confirmCancelInitialWithPaypal:"Ao continuar o pagamento online do cliente ser&aacute; extornado.<br>Voc&ecirc; tem certeza que deseja cancelar esse pedido?",
	confirmCancelClientIsAware:"Voc&ecirc; informou o cliente do cancelamento?",
	confirmCancelRequestReason:"Ao cancelar um pedido voc&ecirc; se responsabiliza pelos danos ao cliente e ao ComendoBem.<br/>Por favor descreva o motivo para o cancelamento:",
	confirmCancelMakeClientAware:"Por favor informe o cliente sobre o cancelamento deste pedido.",
	retrieveAtRestaurant:"Retirar no endere&ccedil;o:",
	restaurantRetrieveAtRestaurant:"Pedido a ser retirado.",
	defaultErrorMsg:"Erro ao carregar dados do pedido. Por favor recarregue esta p&aacute;gina.",
	errorDuringOrderStatusChange:"Houve um erro durante a troca de estado do pedido. Por favor tente novamente.",
	loadAddressFailed:"Houve um erro durante o carregamento de informa&ccedil;&otilde;es de endere&ccedil;o. Por favore tente novamente.",
	mustAcceptOrCancelOrder:"Por favor indique se pedido foi aceito ou cancelado.",
	errorPayPalExpired:'Este pedido foi feito h&aacute; muito tempo, a autoriza&ccedil;&atilde;o de pagamento venceu.<br/>Pedido ser&aacute; cancelado automaticamente.',
	errorPayPalStatusChange:"Houve um erro durante autoriza&ccedil;&atilde;o de pagamento, por favor contacte o suporte do site.",
	retryAuthorization:"Autorizando Pgto...",
	expiredReason:"Pedido cancelado automaticamente pois n&atilde;o houve confirma&ccedil;&atilde;o do pedido no prazo limite de 15 minutos.",
	statusAlreadyCancelled:"Houve altera&ccedil;&otilde;es neste pedido.<br>Ele foi cancelado enquanto voc&ecirc; o visualizava.<br/>Recarregue o pedido para ver a causa do cancelamento.<br/>"
	
	
}